name: ARM Template 

on:
  push:
    branches:
      - none
  workflow_dispatch:

jobs:
  App_Gateway_Deployment:
    runs-on: ubuntu-latest
    if: ${{ vars.INFRA_APP_GATEWAY_DEPLOYMENT == 'YES' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: App_Gateway_Deployment_Install
      run: |
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_ID }} -p ${{ secrets.SERVICE_PRINCIPAL_KEY }} --tenant ${{ secrets.TENANT_ID }}
        deploymentName='MyDeployment'
            sed -i "s|{{.appgatewayname}}|$(AppGateway-Name)|" AppGateway.json
            sed -i "s|{{.appgatewaypublicip}}|$(AppGateway-PublicIP)|" AppGateway.json
            sed -i "s|{{.appgatewayvnet}}|$(AppGateway-VNet)|" AppGateway.json
            sed -i "s|{{.appgatewayexternalid}}|$(AppGateway-PublicIPExternalID)|" AppGateway.json                        
            sed -i "s|{{.location}}|$(location)|" AppGateway.json
            cat AppGateway.json
            az deployment group create --resource-group $(resource-group-name) --name $deploymentName --template-file AppGateway.json
