name: ARM Template 

on:
  push:
    branches:
      - none
  workflow_dispatch:

jobs:
  App_Gateway_Deployment:
    runs-on: ubuntu-latest
    if: ${{ vars.INFRA_APP_GATEWAY_DEPLOYMENT == 'YES' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: App_Gateway_Deployment_Install
      run: |
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_ID }} -p ${{ secrets.SERVICE_PRINCIPAL_KEY }} --tenant ${{ secrets.TENANT_ID }}
        deploymentName='MyDeployment'
            sed -i "s|{{.appgatewayname}}|$(APP_GATEWAY_NAME)|" AppGateway.json
            sed -i "s|{{.appgatewaypublicip}}|$(APPGATEWAY_PUBLICIP)|" AppGateway.json
            sed -i "s|{{.appgatewayvnet}}|$(APP_GATEWAY_VNET)|" AppGateway.json
            sed -i "s|{{.appgatewaysubnet}}|$(APP_GATEWAY_SUBNET)|" AppGateway.json
            sed -i "s|{{.appgatewayexternalid}}|$(APP_GATEWAY_PublicIPExternalID)|" AppGateway.json                        
            sed -i "s|{{.location}}|$(LOCATION_NAME)|" AppGateway.json
            cat AppGateway.json
            az deployment group create --resource-group ${{ vars.RESOURCEGROUP_NAME }} --name $deploymentName --template-file AppGateway.json
