name: ARM Template 

on:
  push:
    branches:
      - none
  workflow_dispatch:

jobs:
  SQL_DB:
    runs-on: ubuntu-latest
    if: ${{ vars.INFRA_STATUS_SQL_DB == 'YES' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SQL_DB_Install
      run: |
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_ID }} -p ${{ secrets.SERVICE_PRINCIPAL_KEY }} --tenant ${{ secrets.TENANT_ID }}
        deploymentName='MyDeployment'
        sed -i "s|{{.servername}}|${{ vars.SQL_SERVER_NAME }}|" SQL-db.json
        sed -i "s|{{.databasename}}|${{ vars.SQL_DB_NAME }}|" SQL-db.json
        sed -i "s|{{.sqlusername}}|${{ vars.SQL_SERVER_USER_NAME }}|" SQL-db.json
        sed -i "s|{{.location}}|${{ vars.LOCATION_NAME }}|" SQL-db.json
        sed -i "s|{{.sqlpassword}}|${{ vars.SQL_SERVER_PASSWORD_NAME }}|" SQL-db.json
        cat SQL-db.json   
        az deployment group create --resource-group ${{ vars.RESOURCEGROUP_NAME }} --name $deploymentName --template-file SQL-db.json
