name: ARM Template 

on:
  push:
    branches:
      - none
  workflow_dispatch:

jobs:
  App_Service_Plan:
    runs-on: ubuntu-latest
    if: ${{ vars.INFRA_WEB_APP_UI_DEPLOYMENT == 'YES' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: App_Service_Plan_Install
      run: |
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_ID }} -p ${{ secrets.SERVICE_PRINCIPAL_KEY }} --tenant ${{ secrets.TENANT_ID }}
        deploymentName='MyDeployment'
        sed -i "s|{{.serviceplanname}}|${{ vars.APP_SERVICE_PLAN_NAME }}|" App_Service_Plan.json
        sed -i "s|{{.location}}|${{ vars.LOCATION_NAME }}|" App_Service_Plan.json
        sed -i "s|{{.spsize}}|${{ vars.APP_SERVICE_PLAN_SIZE }}|" App_Service_Plan.json
        cat App_Service_Plan.json   
        az deployment group create --resource-group ${{ vars.RESOURCEGROUP_NAME }} --name $deploymentName --template-file App_Service_Plan.json
